language: python

python:
  - "3.6"

branches:
  only:
  - master
  - development

install:
  - python3 setup.py install
  - python3 setup.py build_ext --inplace  # for cython

script:
  py.test --cov=mgcpy

after_success:
  - coveralls
